remote_theme: daviddarnes/alembic

navigation_header:
  Home: /
  Joshua Schaferbien's Portfolio:https://jrschaferb.github.io/README.html
  Project 1: https://jrschaferb.github.io/Project%201/schaferbien_Project_1.html
  Project 2: /project2_sfi/project2.html
  Project 3: /project1_bamap/project1.html
  Project 4: /project1_bamap/project1.html

theme: jekyll-theme-time-machine
