remote_theme: daviddarnes/alembic

 navigation_header:
 
  Josh Schaferbien's Portfolio: /jrschaferb.github.io/index.html
  Project 1: /jrschaferb.github.io/Project 1/schaferbien_Project_1.html
  Project 2: /project2_sfi/project2.html
  Project 3: /project1_bamap/project1.html
